language: minimal
services:
  - docker
before_script: cd docker
script:
  - bash run_tests_ci.sh
after_success:
  - bash run_build_release_package.sh
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "gO2h/BToSqWVENYkLTH4i0r7IjHoGZx3xaEjCmmSOsfDdWhjK3u6pqziPs3gKIIKPZiQHWwKW1eCRoR4ZBDatICzLf44JV4sAIjJi7jT3IDkpBLqAgmBiIRyr/6aQrQPZUDgeI2ptZLSnPGW3o2NbUsWs6JdzNws2vpo5qdB+yE5WgOHwQJZN1u0ARe6x1dtykFCPw9Ld+04pxgHjVqKRDd554dsPQYh0uKz9SzD76+8+TAj7D4Yes4HZCTGxmpAH2TZ7MjRHGzVFIkJVyUx4fDcFnNpFsXLzD0eabqhG2wUvkhjLGpmP/CmyuUT3PPKdo6JjjYJQc2DpgZNeVLZgeUOwgyLH5G/NVdiv2ko/nbLzjxYjQqFVJXGGZ2ogfdEw4oJvT3coFdXdNVcvODv+nr0J8Ra67SWJ7O5FwZtrzpzAoVIwG39KM3NERW3EHhwQuQfQkQ9bHj2Oc5rB/2BLV8h6VQEUFNv6AU/nWVOs1NmL/jM+9hlq8P5m0pMu0w2hMn8zd9dqDgoRVqs1me82vvxCeC2C8dchPHXr7LvK7N7zhGlmho6Id4ysbLzf0vYpniDxeE9ec6widQy5EAYpVJgZAwWulZ14KOgMIy+Pb0BvqVsXdYfNZTOJ7BnnI619vVB7APe62KgZlbOdjgHRYgTwaDm3BPRZSGX69gyCJE="
  file:
    - materia-pkg.zip
    - materia-pkg-build-info.yml
  on:
    tags: true
    repo: ucfopen/Materia
notifications:
  slack:
    secure: pbqgHSnFFCEU1iL5Zp8Do0Pcgf23dZ5YjF0bauYAY+Wrgc85DF0m7n/s3Sdw3mTLvmF6Q4JFTqHRfuU30YGQir4QBpnfLKqZuDG11L/J5BqZ1+vKA2byjCOByKVOM1uO4MEbIF+EDsQ6MkGY1PBiatqJ8wcyC0Og/zLyy72oInaClHRRKiTKqQSssZ1ZgDAB6xa7Xb0X72YOZnaxcICuK69VCN93MQwlROq/TyAtj6IHPBnG5vvwutP5UlHBM3tW6CmQeyu8bcGLAwaObHk62Hh065cW8UIFt6L1GVPFNZ8No4J4dA+1CS99ROiRNgrRsWnT/u459SnSE6VJsU/QAw5W+3YBQpCSMMnQZSL8x/J93Qm8cCEAKsliXAOfEl7J3JY5VsxCDJ8OW7ihWwP1LFaSwdwcQTjx9xIvuyTf3x/kLse3Jhb5vQ7bH4jxLNKzlAnLFJok9ytJ+V1CfJmiJ/hcihBEQJRjRXybuk2P4heCoDqYhFCq9bIwErOGVXoXzooE2PM5FSqy1u9Y9ww3o5Qf30GBTDxazVpVCXAjYMl8agamIDWYJpBP9SqOA/wobPB5t06pcyBsZddjJdfx23QIBaahOedb51kacLZVSMycBgZDaEhw7a9W8yH9q9t9DPSNzA1wCGqwiFGonTN0t+vppUwaFlma4E7MuiShKaI=
