# name: materia-django
version: '3.5'

networks:
  backend:

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ../public:/var/www/html/staticfiles:ro
      - ../theme/img:/var/www/html/staticfiles/theme/img:ro
      - uploaded_widgets_django:/var/www/html/staticfiles/widget/:ro
      - ./config/nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - python

  python:
    build:
      context: ../
      dockerfile: materia-app.python.Dockerfile
    networks:
      - backend
    ports:
      - '8001:8001'
    depends_on:
      - mysql
    environment:
      - DJANGO_ENV=dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=materia_dev
      - MYSQL_USER=materia_user
      - MYSQL_PASSWORD=kogneato
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - EMAIL_HOST=host.docker.internal
      - EMAIL_PORT=1025
    volumes:
      - ../app:/var/www/html
      - ../wait_for_it.sh:/var/www/html/wait_for_it.sh
      - uploaded_widgets_django:/var/www/html/staticfiles/widget/
      - ./config/uwsgi/:/etc/uwsgi
    # command: uwsgi --ini=/etc/uwsgi/uwsgi.ini --py-autoreload=2
    command: /wait_for_it.sh mysql:3306 -t 10 -- uwsgi --ini=/etc/uwsgi/uwsgi.ini --py-autoreload=2
    # command: /bin/bash -c '/wait_for_it.sh mysql:3306 -t 10 && yarn install --silent && echo "Building frontend..." && yarn build-for-image && echo "Collecting static files..." && python manage.py collectstatic --noinput && echo "Starting Django server..." && uwsgi --ini=/etc/uwsgi/uwsgi.ini --py-autoreload=2 && python manage.py runserver 0.0.0.0:8001'
  mysql:
    image: mariadb:10.6
    networks:
      - backend
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=materia_dev
      - MYSQL_USER=materia_user
      - MYSQL_PASSWORD=kogneato
    volumes:
      - ./config/mysql/override.cnf:/etc/mysql/conf.d/override.cnf
      - ./backup.sql:/backup.sql

volumes:
  # static_files: {} # compiled js/css and uploaded widgets
  # uploaded_media: {} # uploaded media files
  uploaded_widgets_django: {}
