name: materia-django

networks:
  backend:

services:
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ../app:/var/www/html:ro
      - ./config/nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - python

  python:
    build:
      context: ../
      dockerfile: materia-app.python.Dockerfile
    networks:
      - backend
    ports:
      - '8001:8001'
    depends_on:
      - mysql
    environment:
      - DJANGO_ENV=dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=materia_dev
      - MYSQL_USER=materia_user
      - MYSQL_PASSWORD=kogneato
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - EMAIL_HOST=host.docker.internal
      - EMAIL_PORT=1025
    volumes:
      - ../app:/var/www/html
      - ./config/uwsgi/:/etc/uwsgi
    # command: uwsgi --ini=/etc/uwsgi/uwsgi.ini --py-autoreload=2
    command: /wait_for_it.sh mysql:3306 -t 10 -- uwsgi --ini=/etc/uwsgi/uwsgi.ini --py-autoreload=2

  mysql:
    image: mariadb:10.6
    networks:
      - backend
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=materia_dev
      - MYSQL_USER=materia_user
      - MYSQL_PASSWORD=kogneato
    volumes:
      - ./config/mysql/override.cnf:/etc/mysql/conf.d/override.cnf
